name: dsci575_project

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - jupyterlab
  - ipykernel
  - duckdb 

  - pip:
      - rank-bm25
      - sentence-transformers
      - faiss-cpu
      - transformers
      - huggingface_hub
      - langchain
      - langchain-community
      - langchain-huggingface
      - streamlit
      - python-dotenv
      - duckduckgo-search
      - ragas
      - datasets<4.0